apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfe
  template:
    metadata:
      labels:
        app: myfe
    spec:
      containers:
        - name: myfe
          image: cleowoman/myfe
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myfe-service
spec:
  type: NodePort
  selector:
    app: myfe
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
