name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: cleowoman
      FRONTEND_DIR: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          # Build the Frontend Docker image
          docker build -t cleowoman/myfe ./myfe

          # Log in to Docker Hub using your credentials
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          # Push the Docker images to Docker Hub
          docker push cleowoman/myfe
